-- Social Dev K2 unified whole-game brain v2 extension schema.
-- The legacy G1.5 tables are copied byte-for-byte into the side-by-side DB.
CREATE TABLE IF NOT EXISTS brain_metadata (key TEXT PRIMARY KEY, value_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS legacy_row_migrations (migration_id TEXT PRIMARY KEY, legacy_table TEXT NOT NULL, legacy_pk TEXT NOT NULL, legacy_row_sha256 TEXT NOT NULL, legacy_db_sha256 TEXT NOT NULL, migrated_at_checkpoint TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifact_blobs (blob_id TEXT PRIMARY KEY, sha256 TEXT NOT NULL UNIQUE, size_bytes INTEGER NOT NULL, content_kind TEXT, status TEXT NOT NULL, authority TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifact_instances (instance_id TEXT PRIMARY KEY, blob_id TEXT NOT NULL, relative_path TEXT NOT NULL UNIQUE, generation TEXT, role TEXT, status TEXT NOT NULL, authority TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifact_lineage (lineage_id TEXT PRIMARY KEY, instance_id TEXT NOT NULL, parent_instance_id TEXT, relation TEXT NOT NULL, source_refs_json TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS artifact_references (reference_id TEXT PRIMARY KEY, source_instance_id TEXT, raw_reference TEXT NOT NULL, normalized_kind TEXT NOT NULL, target_id TEXT, status TEXT NOT NULL, authority TEXT NOT NULL, source_location TEXT, note TEXT);
CREATE TABLE IF NOT EXISTS id_namespaces (namespace_id TEXT PRIMARY KEY, domain TEXT NOT NULL, description TEXT NOT NULL, naked_integer_allowed INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS identity_values (identity_id TEXT PRIMARY KEY, namespace_id TEXT NOT NULL, raw_value_text TEXT NOT NULL, canonical_id TEXT NOT NULL, source_refs_json TEXT NOT NULL, status TEXT NOT NULL, authority TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS entity_aliases (alias_id TEXT PRIMARY KEY, alias_value TEXT NOT NULL, namespace_id TEXT NOT NULL, canonical_id TEXT NOT NULL, status TEXT NOT NULL, reason TEXT NOT NULL, source_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS semantic_edges (edge_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, predicate TEXT NOT NULL, object_id TEXT NOT NULL, status TEXT NOT NULL, authority TEXT NOT NULL, source_refs_json TEXT NOT NULL, claim_id TEXT);
CREATE TABLE IF NOT EXISTS edge_claims (claim_id TEXT PRIMARY KEY, edge_id TEXT NOT NULL, claim_status TEXT NOT NULL, confidence TEXT NOT NULL, statement TEXT NOT NULL, source_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS edge_sources (edge_source_id TEXT PRIMARY KEY, edge_id TEXT NOT NULL, source_instance_id TEXT, source_ref TEXT NOT NULL, authority TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS edge_revisions (revision_id TEXT PRIMARY KEY, edge_id TEXT NOT NULL, prior_status TEXT, next_status TEXT NOT NULL, reason TEXT NOT NULL, source_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS implementation_bindings (binding_id TEXT PRIMARY KEY, canonical_id TEXT NOT NULL, implementation_symbol TEXT NOT NULL, layer TEXT NOT NULL, status TEXT NOT NULL, source_refs_json TEXT NOT NULL, test_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS acceptance_bindings (acceptance_id TEXT PRIMARY KEY, canonical_id TEXT NOT NULL, test_id TEXT NOT NULL, scenario TEXT NOT NULL, status TEXT NOT NULL, source_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS usage_classification (usage_id TEXT PRIMARY KEY, artifact_id TEXT NOT NULL, active_status TEXT NOT NULL, classification TEXT NOT NULL, reason TEXT NOT NULL, source_refs_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS derived_artifacts (derived_id TEXT PRIMARY KEY, relative_path TEXT NOT NULL UNIQUE, kind TEXT NOT NULL, source_ids_json TEXT NOT NULL, brain_revision TEXT NOT NULL, sha256 TEXT NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS gap_queue (gap_id TEXT PRIMARY KEY, queue TEXT NOT NULL, subject_id TEXT NOT NULL, missing_predicate TEXT NOT NULL, status TEXT NOT NULL, authority TEXT NOT NULL, source_refs_json TEXT NOT NULL, blocks TEXT NOT NULL, suggested_next_step TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS brain_families (family_id TEXT PRIMARY KEY, label TEXT NOT NULL, authority_layer TEXT NOT NULL, artifact_count INTEGER NOT NULL, claim_count INTEGER NOT NULL, edge_count INTEGER NOT NULL, limitation_count INTEGER NOT NULL, status TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_bindings (product_binding_id TEXT PRIMARY KEY, product_namespace TEXT NOT NULL, product_id TEXT NOT NULL, original_id TEXT NOT NULL, relation TEXT NOT NULL, mutation_allowed INTEGER NOT NULL, status TEXT NOT NULL, source_refs_json TEXT NOT NULL);
